### ISSUE TITLE
希望大佬指明方向，在哪里可以学到 油猴脚本的相关说明

### ISSUE THREAD

**Issue by cctyl** [pdkst/MonkeyScript#26]
想知道油猴脚本的编写格式，还有作用原理，作用时间这些知识，但是不知道要在哪里学习，希望大佬给我指个方向

**Comment by pdkst** [comment]
油猴脚本的头大部分的都可以在油猴脚本插件的文档中找到[参考文档](https://www.tampermonkey.net/documentation.php?ext=dhdg)，用的时候搜索一下就知道了，或者参考一下其他人写的脚本，一般问题不大

其实油猴脚本最重要的是javascript的知识，B站上很多免费的学习资源，可以试着学习看看

**Comment by cctyl** [comment]
谢谢😊


------------------ 原始邮件 ------------------
发件人: pdkst <notifications@github.com&gt;
发送时间: 2020年8月25日 18:06
收件人: pdkst/MonkeyScript <MonkeyScript@noreply.github.com&gt;
抄送: cctyl <2621460357@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[pdkst/MonkeyScript] 希望大佬指明方向，在哪里可以学到 油猴脚本的相关说明 (#26)





 
油猴脚本的头大部分的都可以在油猴脚本插件的文档中找到参考文档，用的时候搜索一下就知道了，或者参考一下其他人写的脚本，一般问题不大
 
其实油猴脚本最重要的是javascript的知识，B站上很多免费的学习资源，可以试着学习看看
